### ISSUE TITLE
[Project Screen] when entering the text in text fields "bottom is overflowed" 

### ISSUE THREAD

**Issue by khomutov-k** [ElBatanony/ProtoFast#12]
Branch: main

Device: android (11 ver), screen - 6.6 inch
 
Step to reproduce:

1. Choose 'WeTube' project from the Projects list
2. Click on the text field with 'Log In' placeholder

Actual: Botton is overflowed label appears 
Expected: User can enter the field without errors

**Comment by khomutov-k** [comment]
![Screenshot_20211010-102320](https://user-images.githubusercontent.com/48259289/136687483-c3857598-4d2f-4761-8509-67ed75e20977.jpg)

**Comment by ElBatanony** [comment]
Fahima offered to handle this issue.
